# Number sizes
PROTOCOL_HEADER_SIZE: int = 1
INT_SIZE: int = 4

# Headers
BET_DATA_HEADER: int = 0x01
BET_CONFIRMATION_HEADER: int = 0x02
AGENCY_ID_HEADER: int = 0x03
BETS_FINISHED_HEADER: int = 0x04
WINNER_IDS_HEADER: int = 0x05
